### ISSUE TITLE
setup test pipeline on abn

### ISSUE THREAD

**Issue by matteodelucchi** [furrer-lab/abn#5] opened 2024-01-18 09:03 UTC
move testpipline from private devel-abn repo to this public repo.

**Comment by j-i-l** [comment] 2024-02-06 14:13
Addressing this issue makes sense only once we have the testing pipeline set up on devel

**Comment by j-i-l** [comment] 2024-03-18 14:49
Duplicate of #25

**Comment by j-i-l** [comment] 2024-03-18 14:50
Duplicate of #25

**Closed by j-i-l** 2024-03-18 14:50 UTC
